_name: 'againvc_vctk'

writer: wandb
ckpt_dir: /home/310505006/AGAIN-VC/checkpoints/again
flag: lrs3_dis_style_sp_sub_normal_ema #lrs3_dis_style_sp_sub_normal

dataset:
    dataset_name: 'lrs3'
    feat_path: /home/310505006/data/lrs3_22feature_500/
    feat:
        - 'mel'
    indexes_path: /home/310505006/data/lrs3_22index_500/indexes.pkl
    seglen: 128
    pitch_path: /home/310505006/data/lrs3_22pitch/
    pitchlen : 147
    ap_path : /home/310505006/data/lrs3_ap_500/
    sp_path : /home/310505006/data/lrs3_sp160_500/
    face_path: /home/310505006/data/face_seeking/ #/home/310505006/data/faceemb_lrs3_mtcnn_margin50_500/

dataloader:
    train:
        batch_size: 32 #2 #32
        shuffle: True
        drop_last: True
    dev:
        batch_size: 64 #2 #64

build:
    model_name: warp_dis_style_sp_sub_normal
    batch_size: 32
    teacher_model:
        params: 
            encoder_params:
                c_in: 80
                c_h: 256
                c_out: 4
                n_conv_blocks: 6 #6
                subsample: [1, 1, 1, 1, 1, 1]
                #head: 1
            decoder_params:
                c_in: 4
                c_h: 256
                c_out: 80
                n_conv_blocks: 6 #6
                upsample: [1, 1, 1, 1, 1, 1]
                #head: 1
            activation_params: 
                act: sigmoid
                params:
                    alpha: 0.1
            pitch_params:
                num_layers: 2
                batch_first: True
                dropout: 0.3
                input_size: 1
                hidden_size: 2 #4
                bidirectional: True
            warp_params:
                in_dim: 512
                out_dim: 256
                mapping_layers: 7
                lastout_dim: 4
                affine_layers: 7
    student_model:
        params: 
            encoder_params:
                c_in: 80
                c_h: 256
                c_out: 4
                n_conv_blocks: 6 #6
                subsample: [1, 1, 1, 1, 1, 1]
                #head: 1
            decoder_params:
                c_in: 4
                c_h: 256
                c_out: 80
                n_conv_blocks: 6 #6
                upsample: [1, 1, 1, 1, 1, 1]
                #head: 1
            activation_params: 
                act: sigmoid
                params:
                    alpha: 0.1
            pitch_params:
                num_layers: 2
                batch_first: True
                dropout: 0.3
                input_size: 1
                hidden_size: 2 #4
                bidirectional: True
            warp_params:
                in_dim: 128 #512
                out_dim: 256
                mapping_layers: 7
                lastout_dim: 4
                affine_layers: 7
    discriminator:
        params:
            in_channel: 80
            condition_channel: 1540 #c_h*n_conv_blocks+lastout_dim
            seglen: 128
            kernel_size: 3
            num_blocks: 4
            num_dis: 3

    optimizer:
        params:
            lr: 0.0005 #0.0005
            betas:
                - 0.9
                - 0.999
            amsgrad: True
            weight_decay: 0 #0.0001
        grad_norm: 3
        criteria: l1
    alpha: 1
    beta: 1
    gamma: 10
    sigma: 1
    delta: 1
    ema: True
    ema_decay: 0.999
